### ISSUE TITLE
Jupyter kernel dies when executing plot function in tutorial "custom_raster_dataset.ipynb"

### ISSUE THREAD

**Issue by mgnolde** [microsoft/torchgeo#841] opened 2022-10-13 20:00 UTC
### Description

In the tutorials folder, there is a tutorial named "custom_raster_dataset.ipynb". In cell 7, some sample data is to be plotted, but executing this method causes a segfault in the Jupyter Kernel. Apparently, the datatype to be handed to the matplotlib plotting function needs to be an array, while in fact it is a tensor.

### Steps to reproduce

Just running all the cells in the notebook will yield the error.

### Version

0.4.0.dev0

**Comment by mgnolde** [comment] 2022-10-13 20:03
Bugfix:
The line ```image = torch.clamp(image / 6000, min=0, max=1)```
needs to be appended with ```.numpy()```:
```image = torch.clamp(image / 6000, min=0, max=1).numpy()```

**Comment by calebrob6** [comment] 2022-10-13 20:57
Hi @mgnolde, I can't reproduce this. I just ran the notebook on Google Colab and locally without hitting a segfault.

![image](https://user-images.githubusercontent.com/1088078/195708627-bebe60a6-65d8-4980-aaac-4d3b7f2cfebf.png)

**Comment by calebrob6** [comment] 2022-10-13 21:00
Please feel free to open a PR that adds a .numpy() to the plot function where you indicate though!

**Comment by adamjstewart** [comment] 2022-10-13 21:02
@mgnolde what versions of PyTorch and matplotlib are you using? Maybe support for PyTorch Tensors was added in a more recent version. Anyway, like @calebrob6 said, there's definitely no harm in explicitly casting to a numpy array, so a PR that does that should be fine. Still curious how to reproduce the issue though. Jupyter doesn't work for me at all on Apple M1 so I can't even test 😢

**Comment by mgnolde** [comment] 2022-10-13 22:02
Thanks @calebrob6 and @adamjstewart for your quick responses! It's interesting that the problem only seems to occur on my side. The idea that matplotlib only recently addded support for tensors sounds very reasonable to me. As proposed, I will open a PR to include the conversion to numpy.
@adamjstewart: I'm running the following versions in a conda environment:

matplotlib-base           3.5.3
pytorch                   1.12.1
jupyter_core              4.11.1

**Comment by adamjstewart** [comment] 2022-10-14 01:27
Closed by #845

**Closed by adamjstewart** 2022-10-14 01:27 UTC
Labels: documentation
