### ISSUE TITLE
OSCDDataModule initialises with batch_size 1, ignoring the configured batch_size 

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1890] opened 2024-02-19 13:58 UTC
### Description

[In the init of OSCD](https://github.com/microsoft/torchgeo/blob/778acd221619dc54dddd1ccd1a159780f9e287af/torchgeo/datamodules/oscd.py#L79C9-L79C57):
```python
super().__init__(OSCD, 1, num_workers, **kwargs)
```
However other datamodules pass along the batchsize: 
[e.g.](https://github.com/microsoft/torchgeo/blob/778acd221619dc54dddd1ccd1a159780f9e287af/torchgeo/datamodules/ucmerced.py#L32C9-L32C70) 
```
super().__init__(UCMerced, batch_size, num_workers, **kwargs)
```

This also affects:
- https://github.com/microsoft/torchgeo/blob/main/torchgeo/datamodules/levircd.py

### Steps to reproduce

Use the datamodule

### Version

dev

**Comment by adamjstewart** [comment] 2024-02-25 13:59
There are two questions here:

> Why do some data modules pass batch size to the data loader while some pass batch size to NRandomCrop?

This is by design. Many datasets such as GID-15 contain very large image scenes (7k x 7k px). These are too large to pass directly to a model and must first be cropped. If the user desires a batch size of 64 and a patch size of 64, instead of loading 64 of these images (may exceed memory) and cropping each to a small image (64 x 64 px), we load a single image and crop it to 64 random subsets. This was done during The Great Data Module Refactor of 2023 (#992). I don't particularly love this solution, but the alternative was for us to add more parameters/complexity.

> Why do OSCD and LEVIR-CD+ _specifically_ do this?

This I'm not sure about. These images aren't honestly _that_ big. We could probably use the normal scheme. I would be open to reviewing which datasets use RandomNCrop and trying to phase it out or replace it with something better. This is also something we plan to upstream to Kornia eventually.

**Comment by adamjstewart** [comment] 2024-02-29 11:46
Can we close this issue, or do we want to take action on these data modules for small-ish images?

**Comment by adamjstewart** [comment] 2024-02-29 11:58
I'm unaware of a more systematic approach.

**Closed by adamjstewart** 2024-02-29 11:58 UTC
Labels: datamodules
