### ISSUE TITLE
Cant import Sentinel 2 Class 

### ISSUE THREAD

**Issue by graceebc9** [microsoft/torchgeo#438] opened 2022-02-28 13:36 UTC
Hi, I have tried with both the normal conda installation of torch and the development one. when I try to import the Sentinel 2 class 
I get the following error: 

from torchgeo.datasets import Sentinel2

cannot import name 'draw_segmentation_masks' from 'torchvision.utils' (/Users/gracecolverd/opt/miniconda3/envs/torch_array/lib/python3.8/site-packages/torchvision/utils.py)

Thanks,
Grace

**Comment by adamjstewart** [comment] 2022-02-28 15:43
TorchGeo requires torchvision 0.10+, it looks like you are using an older version of torchvision. How did you install TorchGeo? It shouldn't be possible to install newer versions of TorchGeo with older versions of torchvision since our `setup.cfg` requires 0.10+ and the Conda and Spack packages correctly list this dependency. What version of TorchGeo are you using?

**Comment by graceebc9** [comment] 2022-02-28 16:40
Thanks adam- 

I installed torchgeo from the 
torchgeo                  0.2.0
torchvision               0.11.2

I first installed via conda and then tried the development one
pip install git+https://github.com/microsoft/torchgeo.git

**Comment by calebrob6** [comment] 2022-02-28 17:13
Hey @graceebc9! Just a quick check -- are you sure you are using the correct environment? It looks like you are using an environment called "torch_array" based on the file path from the exception above.

**Comment by graceebc9** [comment] 2022-02-28 19:16
Hi Caleb 

I have two environments that I tried that both gave the same error. 

for torch_array I have the versions
torchgeo                  0.3.0.dev0
torchvision               0.11.2

**Comment by adamjstewart** [comment] 2022-02-28 21:25
I think @calebrob6 might be right, there seems to be a mismatch between the version of torchvision you think you are using and the actual version you are using. Are you running Python from the command line or via a Jupyter Notebook? Can you run the following code in the same environment you are experiencing issues with and share the output here?
```console
$ python
>>> import sys
>>> sys.version
>>> sys.prefix
>>> import torchvision
>>> torchvision.__version__
>>> torchvision.__file__
>>> from torchvision.utils import draw_segmentation_masks
>>> import torchgeo
>>> torchgeo.__version__
>>> torchgeo.__file__
```

**Comment by calebrob6** [comment] 2022-02-28 21:30
@graceebc9 if we can't figure it out in a few more passes here then I'm happy to hop on a call to debug -- I know package/environment management can be _super_ frustrating

**Comment by calebrob6** [comment] 2022-02-28 22:09
Just to double check, I ran the following commands (in an empty directory):

```bash
conda deactivate
conda create --name torchgeo_test
conda install torchgeo -c conda-forge
conda activate torchgeo_test
python -c "from torchgeo.datasets import Sentinel2"
```

and everything worked okay!

**Comment by graceebc9** [comment] 2022-02-28 23:32
Hi Caleb, I ran the same but in a slightly different order so that the package was installed in the torchgeo_test environment and I got the error copied below. I also tried to import it in a jupyter notebook and the kernel just dies

conda activate torchgeo_test
(torchgeo_test)gracecolverd@dhcp-10-249-174-249 ~ % conda install torchgeo -c con
da-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/gracecolverd/opt/miniconda3/envs/torchgeo_test

  added / updated specs:
    - torchgeo


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ffmpeg-4.3.2               |       hbf27d7b_3        10.5 MB  conda-forge
    gdal-3.4.1                 |   py39h24e6aad_4         1.8 MB  conda-forge
    importlib-metadata-4.11.2  |   py39h6e9494a_0          33 KB  conda-forge
    libgdal-3.4.1              |       he416c16_4         9.5 MB  conda-forge
    libnghttp2-1.47.0          |       h942079c_0         871 KB  conda-forge
    tiledb-2.6.3               |       h190f7ed_0         3.3 MB  conda-forge
    tqdm-4.63.0                |     pyhd8ed1ab_0          80 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        26.1 MB

The following NEW packages will be INSTALLED:

  absl-py            conda-forge/noarch::absl-py-1.0.0-pyhd8ed1ab_0
  affine             conda-forge/noarch::affine-2.3.0-py_0
  aiohttp            conda-forge/osx-64::aiohttp-3.8.1-py39h89e85a6_0
  aiosignal          conda-forge/noarch::aiosignal-1.2.0-pyhd8ed1ab_0
  antlr-python-runt~ conda-forge/noarch::antlr-python-runtime-4.9.3-pyhd8ed1ab_1
  async-timeout      conda-forge/noarch::async-timeout-4.0.2-pyhd8ed1ab_0
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  blinker            conda-forge/noarch::blinker-1.4-py_1
  blosc              conda-forge/osx-64::blosc-1.21.0-he49afe7_0
  boost-cpp          conda-forge/osx-64::boost-cpp-1.74.0-hdbf7018_7
  brotli             conda-forge/osx-64::brotli-1.0.9-h0d85af4_6
  brotli-bin         conda-forge/osx-64::brotli-bin-1.0.9-h0d85af4_6
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py39h89e85a6_1003
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0d85af4_4
  c-ares             conda-forge/osx-64::c-ares-1.18.1-h0d85af4_0
  ca-certificates    conda-forge/osx-64::ca-certificates-2021.10.8-h033912b_0
  cachetools         conda-forge/noarch::cachetools-5.0.0-pyhd8ed1ab_0
  cairo              conda-forge/osx-64::cairo-1.16.0-he01c77b_1009
  certifi            conda-forge/osx-64::certifi-2021.10.8-py39h6e9494a_1
  cffi               conda-forge/osx-64::cffi-1.15.0-py39he338e87_0
  cfitsio            conda-forge/osx-64::cfitsio-4.0.0-hb20e66c_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.0.12-pyhd8ed1ab_0
  click              conda-forge/osx-64::click-8.0.4-py39h6e9494a_0
  click-plugins      conda-forge/noarch::click-plugins-1.1.1-py_0
  cligj              conda-forge/noarch::cligj-0.7.2-pyhd8ed1ab_1
  colorama           conda-forge/noarch::colorama-0.4.4-pyh9f0ad1d_0
  cryptography       conda-forge/osx-64::cryptography-36.0.1-py39h209aa08_0
  curl               conda-forge/osx-64::curl-7.81.0-hf45b732_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  efficientnet-pyto~ conda-forge/noarch::efficientnet-pytorch-0.6.3-pyh9f0ad1d_0
  einops             conda-forge/noarch::einops-0.4.0-pyhd8ed1ab_0
  expat              conda-forge/osx-64::expat-2.4.6-h96cf925_0
  ffmpeg             conda-forge/osx-64::ffmpeg-4.3.2-hbf27d7b_3
  fiona              conda-forge/osx-64::fiona-1.8.21-py39haa9df5e_0
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-hab24e00_0
  fontconfig         conda-forge/osx-64::fontconfig-2.13.96-h10f422b_0
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0
  fonttools          conda-forge/osx-64::fonttools-4.29.1-py39h89e85a6_0
  freetype           conda-forge/osx-64::freetype-2.10.4-h4cff582_1
  freexl             conda-forge/osx-64::freexl-1.0.6-h0d85af4_0
  frozenlist         conda-forge/osx-64::frozenlist-1.3.0-py39h89e85a6_0
  fsspec             conda-forge/noarch::fsspec-2022.2.0-pyhd8ed1ab_0
  future             conda-forge/osx-64::future-0.18.2-py39h6e9494a_4
  gdal               conda-forge/osx-64::gdal-3.4.1-py39h24e6aad_4
  geos               conda-forge/osx-64::geos-3.10.2-he49afe7_0
  geotiff            conda-forge/osx-64::geotiff-1.7.0-h0ca5f94_6
  gettext            conda-forge/osx-64::gettext-0.19.8.1-hd1a6beb_1008
  giflib             conda-forge/osx-64::giflib-5.2.1-hbcb3906_2
  gmp                conda-forge/osx-64::gmp-6.2.1-h2e338ed_0
  gnutls             conda-forge/osx-64::gnutls-3.6.13-h756fd2b_1
  google-auth        conda-forge/noarch::google-auth-2.6.0-pyh6c4a22f_1
  google-auth-oauth~ conda-forge/noarch::google-auth-oauthlib-0.4.6-pyhd8ed1ab_0
  grpcio             conda-forge/osx-64::grpcio-1.44.0-py39h757451a_0
  hdf4               conda-forge/osx-64::hdf4-4.2.15-hefd3b78_3
  hdf5               conda-forge/osx-64::hdf5-1.12.1-nompi_h2f0ef1a_103
  icu                conda-forge/osx-64::icu-69.1-he49afe7_0
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  importlib-metadata conda-forge/osx-64::importlib-metadata-4.11.2-py39h6e9494a_0
  jbig               conda-forge/osx-64::jbig-2.1-h0d85af4_2003
  joblib             conda-forge/noarch::joblib-1.1.0-pyhd8ed1ab_0
  jpeg               conda-forge/osx-64::jpeg-9e-h0d85af4_0
  json-c             conda-forge/osx-64::json-c-0.15-hcb556a6_0
  kealib             conda-forge/osx-64::kealib-1.4.14-ha22a8b1_3
  kiwisolver         conda-forge/osx-64::kiwisolver-1.3.2-py39hf018cea_1
  kornia             conda-forge/noarch::kornia-0.6.3-pyhd8ed1ab_0
  krb5               conda-forge/osx-64::krb5-1.19.2-hcfbf3a7_3
  lame               conda-forge/osx-64::lame-3.100-h35c211d_1001
  lcms2              conda-forge/osx-64::lcms2-2.12-h577c468_0
  lerc               conda-forge/osx-64::lerc-3.0-he49afe7_0
  libblas            conda-forge/osx-64::libblas-3.9.0-13_osx64_mkl
  libbrotlicommon    conda-forge/osx-64::libbrotlicommon-1.0.9-h0d85af4_6
  libbrotlidec       conda-forge/osx-64::libbrotlidec-1.0.9-h0d85af4_6
  libbrotlienc       conda-forge/osx-64::libbrotlienc-1.0.9-h0d85af4_6
  libcblas           conda-forge/osx-64::libcblas-3.9.0-13_osx64_mkl
  libcurl            conda-forge/osx-64::libcurl-7.81.0-hf45b732_0
  libcxx             conda-forge/osx-64::libcxx-12.0.1-habf9029_1
  libdap4            conda-forge/osx-64::libdap4-3.20.6-h3e144a0_2
  libdeflate         conda-forge/osx-64::libdeflate-1.10-h0d85af4_0
  libedit            conda-forge/osx-64::libedit-3.1.20191231-h0678c8f_2
  libev              conda-forge/osx-64::libev-4.33-haf1e3a3_1
  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5
  libgdal            conda-forge/osx-64::libgdal-3.4.1-he416c16_4
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-9_3_0_h6c81a4c_23
  libgfortran5       conda-forge/osx-64::libgfortran5-9.3.0-h6c81a4c_23
  libglib            conda-forge/osx-64::libglib-2.70.2-hf1fb8c0_4
  libiconv           conda-forge/osx-64::libiconv-1.16-haf1e3a3_0
  libkml             conda-forge/osx-64::libkml-1.3.0-h8fd9edb_1014
  liblapack          conda-forge/osx-64::liblapack-3.9.0-13_osx64_mkl
  libnetcdf          conda-forge/osx-64::libnetcdf-4.8.1-nompi_h6609ca0_101
  libnghttp2         conda-forge/osx-64::libnghttp2-1.47.0-h942079c_0
  libpng             conda-forge/osx-64::libpng-1.6.37-h7cec526_2
  libpq              conda-forge/osx-64::libpq-14.2-hea3049e_0
  libprotobuf        conda-forge/osx-64::libprotobuf-3.19.4-hcf210ce_0
  librttopo          conda-forge/osx-64::librttopo-1.1.0-hec60dd8_9
  libspatialindex    conda-forge/osx-64::libspatialindex-1.9.3-he49afe7_4
  libspatialite      conda-forge/osx-64::libspatialite-5.0.1-h88e7940_14
  libssh2            conda-forge/osx-64::libssh2-1.10.0-h52ee1ee_2
  libtiff            conda-forge/osx-64::libtiff-4.3.0-h17f2ce3_3
  libwebp            conda-forge/osx-64::libwebp-1.2.2-h28dabe5_0
  libwebp-base       conda-forge/osx-64::libwebp-base-1.2.2-h0d85af4_1
  libxcb             conda-forge/osx-64::libxcb-1.13-h0d85af4_1004
  libxml2            conda-forge/osx-64::libxml2-2.9.12-h7e28ab6_1
  libzip             conda-forge/osx-64::libzip-1.8.0-h8b0c345_1
  libzlib            conda-forge/osx-64::libzlib-1.2.11-h9173be1_1013
  llvm-openmp        conda-forge/osx-64::llvm-openmp-13.0.1-hda6cdc1_0
  lz4-c              conda-forge/osx-64::lz4-c-1.9.3-he49afe7_1
  markdown           conda-forge/noarch::markdown-3.3.6-pyhd8ed1ab_0
  matplotlib-base    conda-forge/osx-64::matplotlib-base-3.5.1-py39hb07454d_0
  mkl                conda-forge/osx-64::mkl-2022.0.0-h89fa619_782
  multidict          conda-forge/osx-64::multidict-6.0.2-py39h89e85a6_0
  munch              conda-forge/noarch::munch-2.5.0-py_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  ncurses            conda-forge/osx-64::ncurses-6.3-he49afe7_0
  nettle             conda-forge/osx-64::nettle-3.6-hedd7734_0
  ninja              conda-forge/osx-64::ninja-1.10.2-h940c156_1
  nspr               conda-forge/osx-64::nspr-4.32-hcd9eead_1
  nss                conda-forge/osx-64::nss-3.74-h31e2bf1_0
  numpy              conda-forge/osx-64::numpy-1.22.2-py39h9d9ce41_0
  oauthlib           conda-forge/noarch::oauthlib-3.2.0-pyhd8ed1ab_0
  omegaconf          conda-forge/osx-64::omegaconf-2.1.1-py39h6e9494a_1
  openh264           conda-forge/osx-64::openh264-2.1.1-hfd3ada9_0
  openjpeg           conda-forge/osx-64::openjpeg-2.4.0-h6e7aa92_1
  openssl            conda-forge/osx-64::openssl-1.1.1l-h0d85af4_0
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0
  pcre               conda-forge/osx-64::pcre-8.45-he49afe7_0
  pillow             conda-forge/osx-64::pillow-9.0.1-py39hd2c7aa1_2
  pip                conda-forge/noarch::pip-22.0.3-pyhd8ed1ab_0
  pixman             conda-forge/osx-64::pixman-0.40.0-hbcb3906_0
  poppler            conda-forge/osx-64::poppler-22.01.0-h9573804_0
  poppler-data       conda-forge/noarch::poppler-data-0.4.11-hd8ed1ab_0
  postgresql         conda-forge/osx-64::postgresql-14.2-he8fe76e_0
  pretrainedmodels   conda-forge/noarch::pretrainedmodels-0.7.4-pyhd8ed1ab_2
  proj               conda-forge/osx-64::proj-8.2.1-h1512c50_0
  protobuf           conda-forge/osx-64::protobuf-3.19.4-py39h9fcab8e_0
  pthread-stubs      conda-forge/osx-64::pthread-stubs-0.4-hc929b4f_1001
  pyasn1             conda-forge/noarch::pyasn1-0.4.8-py_0
  pyasn1-modules     conda-forge/noarch::pyasn1-modules-0.2.7-py_0
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pydeprecate        conda-forge/noarch::pydeprecate-0.3.2-pyhd8ed1ab_0
  pyjwt              conda-forge/noarch::pyjwt-2.3.0-pyhd8ed1ab_1
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.7-pyhd8ed1ab_0
  pyproj             conda-forge/osx-64::pyproj-3.3.0-py39h074cefc_1
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py39h6e9494a_4
  python             conda-forge/osx-64::python-3.9.10-h1dd9edd_2_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python_abi         conda-forge/osx-64::python_abi-3.9-2_cp39
  pytorch            conda-forge/osx-64::pytorch-1.10.2-cpu_py39h19568cb_1
  pytorch-lightning  conda-forge/noarch::pytorch-lightning-1.5.10-pyhd8ed1ab_0
  pyu2f              conda-forge/noarch::pyu2f-0.1.5-pyhd8ed1ab_0
  pyyaml             conda-forge/osx-64::pyyaml-6.0-py39h89e85a6_3
  rasterio           conda-forge/osx-64::rasterio-1.2.10-py39h68da641_4
  readline           conda-forge/osx-64::readline-8.1-h05e3726_0
  requests           conda-forge/noarch::requests-2.27.1-pyhd8ed1ab_0
  requests-oauthlib  conda-forge/noarch::requests-oauthlib-1.3.1-pyhd8ed1ab_0
  rsa                conda-forge/noarch::rsa-4.8-pyhd8ed1ab_0
  rtree              conda-forge/osx-64::rtree-0.9.7-py39h7d0d40a_3
  scikit-learn       conda-forge/osx-64::scikit-learn-1.0.2-py39hd4eea88_0
  scipy              conda-forge/osx-64::scipy-1.8.0-py39h056f1c0_1
  segmentation-mode~ conda-forge/noarch::segmentation-models-pytorch-0.2.1-pyhd8ed1ab_0
  setuptools         conda-forge/osx-64::setuptools-59.5.0-py39h6e9494a_0
  shapely            conda-forge/osx-64::shapely-1.8.0-py39hbfbc381_5
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sleef              conda-forge/osx-64::sleef-3.5.1-h6db0672_2
  snuggs             conda-forge/noarch::snuggs-1.4.7-py_0
  sqlite             conda-forge/osx-64::sqlite-3.37.0-h23a322b_0
  tbb                conda-forge/osx-64::tbb-2021.5.0-h940c156_0
  tensorboard        conda-forge/noarch::tensorboard-2.8.0-pyhd8ed1ab_1
  tensorboard-data-~ conda-forge/osx-64::tensorboard-data-server-0.6.0-py39h209aa08_1
  tensorboard-plugi~ conda-forge/noarch::tensorboard-plugin-wit-1.8.1-pyhd8ed1ab_0
  threadpoolctl      conda-forge/noarch::threadpoolctl-3.1.0-pyh8a188c0_0
  tiledb             conda-forge/osx-64::tiledb-2.6.3-h190f7ed_0
  timm               conda-forge/noarch::timm-0.4.12-pyhd8ed1ab_0
  tk                 conda-forge/osx-64::tk-8.6.12-h5dbffcc_0
  torchgeo           conda-forge/noarch::torchgeo-0.2.0-pyhd8ed1ab_0
  torchmetrics       conda-forge/noarch::torchmetrics-0.7.2-pyhd8ed1ab_0
  torchvision        conda-forge/osx-64::torchvision-0.11.3-cpu_py39h7c5a76e_1
  tqdm               conda-forge/noarch::tqdm-4.63.0-pyhd8ed1ab_0
  typing-extensions  conda-forge/noarch::typing-extensions-4.1.1-hd8ed1ab_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.1.1-pyha770c72_0
  tzcode             conda-forge/osx-64::tzcode-2021e-h0d85af4_0
  tzdata             conda-forge/noarch::tzdata-2021e-he74cb21_0
  unicodedata2       conda-forge/osx-64::unicodedata2-14.0.0-py39h89e85a6_0
  urllib3            conda-forge/noarch::urllib3-1.26.8-pyhd8ed1ab_1
  werkzeug           conda-forge/noarch::werkzeug-2.0.3-pyhd8ed1ab_1
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  x264               conda-forge/osx-64::x264-1!161.3030-h0d85af4_1
  xerces-c           conda-forge/osx-64::xerces-c-3.2.3-h6564042_4
  xorg-libxau        conda-forge/osx-64::xorg-libxau-1.0.9-h35c211d_0
  xorg-libxdmcp      conda-forge/osx-64::xorg-libxdmcp-1.1.3-h35c211d_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  yaml               conda-forge/osx-64::yaml-0.2.5-h0d85af4_2
  yarl               conda-forge/osx-64::yarl-1.7.2-py39h89e85a6_1
  zipp               conda-forge/noarch::zipp-3.7.0-pyhd8ed1ab_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h9173be1_1013
  zstd               conda-forge/osx-64::zstd-1.5.2-h582d3a0_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
libgdal-3.4.1        | 9.5 MB    | ###################################### | 100%
importlib-metadata-4 | 33 KB     | ###################################### | 100%
tqdm-4.63.0          | 80 KB     | ###################################### | 100%
tiledb-2.6.3         | 3.3 MB    | ###################################### | 100%
gdal-3.4.1           | 1.8 MB    | ###################################### | 100%
ffmpeg-4.3.2         | 10.5 MB   | ###################################### | 100%
libnghttp2-1.47.0    | 871 KB    | ###################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(torchgeo_test)gracecolverd@dhcp-10-249-174-249 ~ % python -c "from torchgeo.datasets import Sentinel2"
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

**Comment by calebrob6** [comment] 2022-02-28 23:43
Hmmmm, now this may be a pytorch problem. I'm seeing these related (very recent) threads:
- https://stackoverflow.com/questions/70830755/intel-mkl-fatal-error-this-system-does-not-meet-the-minimum-requirements-for-us
- https://github.com/pytorch/pytorch/issues/70394

Are you using an M1 Macbook Pro?

**Comment by graceebc9** [comment] 2022-03-01 11:01
M1 Macbook AIr

**Comment by graceebc9** [comment] 2022-03-01 11:25
> 

Hi @adamjstewart , I ran the stuff you pasted - it looks like the torchvision being used is not the same as that which is printed from conda list (torchvision               0.11.2)

Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.8.5 (default, Sep  4 2020, 02:22:02) \n[Clang 10.0.0 ]'
>>> sys.prefix
'/Users/gracecolverd/opt/miniconda3/envs/geo_torch'
>>> import torchvision
>>> torchvision.__version__
'0.5.0'
>>> torchvision.__file__
'/Users/gracecolverd/opt/miniconda3/envs/geo_torch/lib/python3.8/site-packages/torchvision/__init__.py'
>>> from torchvision.utils import draw_segmentation_masks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'draw_segmentation_masks' from 'torchvision.utils' (/Users/gracecolverd/opt/miniconda3/envs/geo_torch/lib/python3.8/site-packages/torchvision/utils.py)
>>> import torchgeo
>>> torchgeo.__version__
'0.2.0'
>>> torchgeo.__file__
'/Users/gracecolverd/opt/miniconda3/envs/geo_torch/lib/python3.8/site-packages/torchgeo/__init__.py'
>>>

**Comment by graceebc9** [comment] 2022-03-01 14:58
Is there a way I can fix which torchvision it pulls?

**Comment by adamjstewart** [comment] 2022-03-01 17:34
You'll need to set your `PYTHONPATH` appropriately. I don't personally use pip or conda, but for these package managers you normally don't need to set anything since all of the libraries are installed to a single prefix. If `PYTHONPATH` isn't set, Python will only search it's own site-packages directory for packages/modules. So first I would take a look at your `PYTHONPATH` and maybe `PYTHONHOME` environment variables and make sure that they are what you expect them to be.

**Comment by adamjstewart** [comment] 2022-03-01 21:18
I'm going to close this because it's not a bug in TorchGeo's setup.cfg or in our Conda/Spack build recipes, but I'm happy to continue to debug your environment issues if you still need help.

**Closed by adamjstewart** 2022-03-01 21:18 UTC

**Comment by graceebc9** [comment] 2022-03-01 21:20
The tip from the comment in this stackq solved it - thanks https://stackoverflow.com/questions/70830755/intel-mkl-fatal-error-this-system-does-not-meet-the-minimum-requirements-for-us
