### ISSUE TITLE
torchgeo install in google colab

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#1054] opened 2023-01-27 20:16 UTC
### Description

I wanted to check a potential bug with a reproducible example in a colab notebook and found that there is some installation issue.

```
%pip install torchgeo

from torchgeo.trainers import ClassificationTask
```

`ContextualVersionConflict: (Pygments 2.6.1 (/usr/local/lib/python3.8/dist-packages), Requirement.parse('pygments<3.0.0,>=2.14.0'), {'rich'})`

### Steps to reproduce

[Notebook](https://colab.research.google.com/drive/1zK4uXLPGOkNWqRuqFszR9opg2bnFzDb1?usp=sharing)

### Version

0.4.0

**Comment by adamjstewart** [comment] 2023-01-27 20:42
Still investigating this, but I find it hilarious that pip installs a broken environment and blames it on existing installations even when you ignore them:
```console
$ pip install --ignore-installed --prefix=~/Downloads/test torchgeo
...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pycocotools 2.0.2 requires cython>=0.27.3, which is not installed.
geopandas 0.11.1 requires shapely<2,>=1.7, but you have shapely 2.0.0 which is incompatible.
```
Like if pycocotools requires cython then why didn't you install it??

**Comment by adamjstewart** [comment] 2023-01-27 20:43
Bug can be reproduced with a simpler import:
```python
import pytorch_lightning
```

**Comment by adamjstewart** [comment] 2023-01-27 20:45
@pradyunsg apologies for tagging you outside of the Spack repo but we're seeing several issues with pip installation and figured you might be interested. If I'm able to figure out exactly what's going on I'll open an issue on the pip repo.

**Comment by adamjstewart** [comment] 2023-01-27 21:15
Adding to the mystery:
```console
$ pip list
...
Pygments                      2.14.0
```
```pycon
>>> import pygments
>>> pygments.__version__
2.6.1
```
It's possible that there are two different versions of pygments installed, and pip failed to uninstall the incompatible version. I'm not sure why 2.6.1 is found first in the `PYTHONPATH` though.

**Comment by adamjstewart** [comment] 2023-01-27 21:30
I'm starting to think this is actually a Jupyter Notebook problem similar to #765. If you "Restart Runtime" and run the cells again, everything works fine. 

My theory is that Pygments is automatically imported by the runtime environment (it's a dependency of notebook), so even after you `%pip install` a newer version, the old version is still cached in Python's import cache. So technically Pygments 2.6.1 isn't installed, 2.14.0 is. But PyTorch Lightning finds the 2.6.1 version from the cache and chokes because it isn't compatible with other installed packages.

As for how to fix this mess? Not sure. I hate telling users "oh you just have to run every notebook twice for it to work obviously". Not sure if it's possible to reload the import via importlib.

**Comment by adamjstewart** [comment] 2023-01-27 21:35
Tried adding:
```
%load_ext autoreload
%autoreload 2
```
after the pip install but it didn't help.

**Comment by hlydecker** [comment] 2023-02-07 22:47
Automatically restarting the runtime after install torchgeo would help to improve the user experience. The Pygments error message doesn't show up on stack so it can be a bit intimidating to users. 

One possible solution is to add the following code into the chunk where you install torchgeo:

```python
%pip install torchgeo

import os
os.kill(os.getpid(), 9)
```

This will automatically kill the runtime, causing it to restart. One downside here is that Google Colab will tell the user that the Colab has crashed unexpectedly. But you can proceed to execute the rest of the code with no additional user effort to manually restart the runtime, etc.

**Comment by adamjstewart** [comment] 2023-02-07 23:05
This is also problematic because our notebook tests would likely fail. We test all notebooks to ensure that they run without crashing.

A longer term solution would be for Google Colab to include more recent versions of these common libraries by default. They've been quite slow to upgrade (only recently upgraded from Python 3.7 to 3.8) but have said they would upgrade more frequently in the future. We'll see if that's actually the case.

**Comment by adamjstewart** [comment] 2023-03-18 16:35
Haven't given up on this just yet: https://github.com/Lightning-AI/lightning/issues/17136

**Comment by pradyunsg** [comment] 2023-03-20 18:21
I have ~no idea what's being discussed here but I see a mention for me from Jan now. Is there an easy reproducer for this that I can look at?

**Comment by adamjstewart** [comment] 2023-03-30 17:04
Fixed by https://github.com/googlecolab/colabtools/issues/3514 and https://github.com/Lightning-AI/lightning/pull/17156

**Closed by adamjstewart** 2023-03-30 17:04 UTC
Labels: documentation
